sonar.projectKey=MoedemErrachi_ARSII_backend
sonar.organization=moedemerrachi
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.ts,**/*.test.ts,**/config/**,**/docs/**,**/server.ts,**/app.ts
sonar.test.inclusions=**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
