sonar.projectKey=MoedemErrachi_ARSII_chatbot
sonar.organization=moedemerrachi
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/coverage.xml
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.cpd.exclusions=**/test_*.py
