sonar.projectKey=MoedemErrachi_ARSII_chatbot
sonar.organization=moedemerrachi
sonar.sources=app
sonar.tests=app/ocr/tests
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/coverage.xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.cpd.exclusions=**/*_test.py
